# INPUT AND SECONDARY 
units   : input.tsv
species : horse
ref     : goldenPath
bucket  : wags
alias   : s3
profile : slurm

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
tmp_dir :
  sort_tmp  : /path/to/proc/dir
  fastq_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# BQSR INTERVAL PARAMS
contig_n_size : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : goldenPath.Ec_build-3.0_wMSY.dict
ref_fasta : /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)
known_sites :
  dbsnp_snp_vcf  : /home/refgen/horse/goldenPath/resources/equus_caballus.chrIDmod.vcf.gz
  mnec2m_snp_vcf : /home/refgen/horse/goldenPath/resources/MNEc2M.EquCab3.09182018.recode.rmGT.refseqnames.chrIDmod.vcf.gz

# SV CONDA ENVS
conda_envs :
  delly  : delly
  gridss : gridss
  smoove : smoove
  manta  : manta
