# INPUT AND SECONDARY
units   : input.tsv
species : dog
ref     : canfam4
bucket  : wags
alias   : s3Fried
profile : slurm

# SINGULARITY IMAGE
sif : /path/to/WAGS/wags.sif

# SORTSAM TEMP DIR
tmp_dir :
  sort_tmp  : /path/to/proc/dir
  fastq_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# INTERVAL SIZE SCATTER
nrun_length  : 50
scatter_size : 50

# REFERENCE FILES 
ref_fasta : /home/refgen/dog/canfam4/canFam4.fa
ref_dict  : canFam4.dict
ref_gtf   : /home/refgen/dog/canfam4/UU_Cfam_GSD_1.0_ROSY.refSeq.ensformat.gtf.gz

# RECAL
indel_recalibration_tranche_values    : ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
snp_recalibration_tranche_values      : ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0" ]
snp_recalibration_annotation_values   : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]

indel_filter_level : 99.7
snp_filter_level   : 99.7

# RESOURCE FILES (FROM CONTAINER)
known_sites :
    dbsnp_indels_vcf : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf
    dbsnp_snp_vcf    : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf
    broad_snp_vcf    : /home/refgen/dog/canfam4/resources/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf
    axelsson_snp_vcf : /home/refgen/dog/canfam4/resources/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf
    illumina_snp_vcf : /home/refgen/dog/canfam4/resources/canFam4.illumina.snps.sorted.fixed.header.chr.vcf

# ALLELE FREQUENCY FOR COMPARISON TO POPULATION
allele_freq : 0.005

# RANDOM PARAMS
excess_het_threshold : 54.69

# SV CONDA ENVS
conda_envs :
    delly  : delly
    gridss : gridss
    lumpy  : lumpy
    manta  : manta

