latency-wait: "5"
jobscript: "lsf_jobscript.sh"
use-conda: "False"
use-singularity: "False"
printshellcmds: "False"
restart-times: "2"
jobs: "300"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
cluster-cancel: "lsf_cancel.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"